/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScolariteRouteImport } from './routes/scolarite'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PresencesRouteImport } from './routes/presences'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EnseignantsRouteImport } from './routes/enseignants'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScolariteRoute = ScolariteRouteImport.update({
  id: '/scolarite',
  path: '/scolarite',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencesRoute = PresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EnseignantsRoute = EnseignantsRouteImport.update({
  id: '/enseignants',
  path: '/enseignants',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRoute
  '/enseignants': typeof EnseignantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/presences': typeof PresencesRoute
  '/register': typeof RegisterRoute
  '/scolarite': typeof ScolariteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRoute
  '/enseignants': typeof EnseignantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/presences': typeof PresencesRoute
  '/register': typeof RegisterRoute
  '/scolarite': typeof ScolariteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRoute
  '/enseignants': typeof EnseignantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/presences': typeof PresencesRoute
  '/register': typeof RegisterRoute
  '/scolarite': typeof ScolariteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/forgot-password'
    | '/login'
    | '/notes'
    | '/parametres'
    | '/presences'
    | '/register'
    | '/scolarite'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/forgot-password'
    | '/login'
    | '/notes'
    | '/parametres'
    | '/presences'
    | '/register'
    | '/scolarite'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/classes'
    | '/dashboard'
    | '/eleves'
    | '/enseignants'
    | '/forgot-password'
    | '/login'
    | '/notes'
    | '/parametres'
    | '/presences'
    | '/register'
    | '/scolarite'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  DashboardRoute: typeof DashboardRoute
  ElevesRoute: typeof ElevesRoute
  EnseignantsRoute: typeof EnseignantsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  ParametresRoute: typeof ParametresRoute
  PresencesRoute: typeof PresencesRoute
  RegisterRoute: typeof RegisterRoute
  ScolariteRoute: typeof ScolariteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scolarite': {
      id: '/scolarite'
      path: '/scolarite'
      fullPath: '/scolarite'
      preLoaderRoute: typeof ScolariteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presences': {
      id: '/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof PresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enseignants': {
      id: '/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof EnseignantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  DashboardRoute: DashboardRoute,
  ElevesRoute: ElevesRoute,
  EnseignantsRoute: EnseignantsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  ParametresRoute: ParametresRoute,
  PresencesRoute: PresencesRoute,
  RegisterRoute: RegisterRoute,
  ScolariteRoute: ScolariteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
