/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScolariteRouteImport } from './routes/scolarite'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PresencesRouteImport } from './routes/presences'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MonProfilRouteImport } from './routes/mon-profil'
import { Route as MonAbonnementRouteImport } from './routes/mon-abonnement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EnseignantsRouteImport } from './routes/enseignants'
import { Route as EmploiDuTempsRouteImport } from './routes/emploi-du-temps'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ChangerMotDePasseRouteImport } from './routes/changer-mot-de-passe'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElevesStudentIdRouteImport } from './routes/eleves.$studentId'
import { Route as ApiPublicSuperAdminRouteImport } from './routes/api/public/super-admin'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'
import { Route as ApiPublicRegisterSchoolRouteImport } from './routes/api/public/register-school'
import { Route as ApiPublicAdminUsersRouteImport } from './routes/api/public/admin-users'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScolariteRoute = ScolariteRouteImport.update({
  id: '/scolarite',
  path: '/scolarite',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencesRoute = PresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MonProfilRoute = MonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MonAbonnementRoute = MonAbonnementRouteImport.update({
  id: '/mon-abonnement',
  path: '/mon-abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EnseignantsRoute = EnseignantsRouteImport.update({
  id: '/enseignants',
  path: '/enseignants',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploiDuTempsRoute = EmploiDuTempsRouteImport.update({
  id: '/emploi-du-temps',
  path: '/emploi-du-temps',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangerMotDePasseRoute = ChangerMotDePasseRouteImport.update({
  id: '/changer-mot-de-passe',
  path: '/changer-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesStudentIdRoute = ElevesStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => ElevesRoute,
} as any)
const ApiPublicSuperAdminRoute = ApiPublicSuperAdminRouteImport.update({
  id: '/api/public/super-admin',
  path: '/api/public/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterSchoolRoute = ApiPublicRegisterSchoolRouteImport.update({
  id: '/api/public/register-school',
  path: '/api/public/register-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminUsersRoute = ApiPublicAdminUsersRouteImport.update({
  id: '/api/public/admin-users',
  path: '/api/public/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/classes': typeof ClassesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRouteWithChildren
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/enseignants': typeof EnseignantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/mon-profil': typeof MonProfilRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/parent': typeof ParentRoute
  '/parents': typeof ParentsRoute
  '/presences': typeof PresencesRoute
  '/register': typeof RegisterRoute
  '/scolarite': typeof ScolariteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/eleves/$studentId': typeof ElevesStudentIdRoute
  '/api/public/admin-users': typeof ApiPublicAdminUsersRoute
  '/api/public/register-school': typeof ApiPublicRegisterSchoolRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/super-admin': typeof ApiPublicSuperAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/classes': typeof ClassesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRouteWithChildren
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/enseignants': typeof EnseignantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/mon-profil': typeof MonProfilRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/parent': typeof ParentRoute
  '/parents': typeof ParentsRoute
  '/presences': typeof PresencesRoute
  '/register': typeof RegisterRoute
  '/scolarite': typeof ScolariteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/eleves/$studentId': typeof ElevesStudentIdRoute
  '/api/public/admin-users': typeof ApiPublicAdminUsersRoute
  '/api/public/register-school': typeof ApiPublicRegisterSchoolRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/super-admin': typeof ApiPublicSuperAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/classes': typeof ClassesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/eleves': typeof ElevesRouteWithChildren
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/enseignants': typeof EnseignantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/mon-profil': typeof MonProfilRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/parent': typeof ParentRoute
  '/parents': typeof ParentsRoute
  '/presences': typeof PresencesRoute
  '/register': typeof RegisterRoute
  '/scolarite': typeof ScolariteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/eleves/$studentId': typeof ElevesStudentIdRoute
  '/api/public/admin-users': typeof ApiPublicAdminUsersRoute
  '/api/public/register-school': typeof ApiPublicRegisterSchoolRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/super-admin': typeof ApiPublicSuperAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annonces'
    | '/changer-mot-de-passe'
    | '/classes'
    | '/confidentialite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/forgot-password'
    | '/login'
    | '/mon-abonnement'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/parent'
    | '/parents'
    | '/presences'
    | '/register'
    | '/scolarite'
    | '/sitemap.xml'
    | '/super-admin'
    | '/unauthorized'
    | '/eleves/$studentId'
    | '/api/public/admin-users'
    | '/api/public/register-school'
    | '/api/public/seed-demo'
    | '/api/public/super-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annonces'
    | '/changer-mot-de-passe'
    | '/classes'
    | '/confidentialite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/forgot-password'
    | '/login'
    | '/mon-abonnement'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/parent'
    | '/parents'
    | '/presences'
    | '/register'
    | '/scolarite'
    | '/sitemap.xml'
    | '/super-admin'
    | '/unauthorized'
    | '/eleves/$studentId'
    | '/api/public/admin-users'
    | '/api/public/register-school'
    | '/api/public/seed-demo'
    | '/api/public/super-admin'
  id:
    | '__root__'
    | '/'
    | '/annonces'
    | '/changer-mot-de-passe'
    | '/classes'
    | '/confidentialite'
    | '/dashboard'
    | '/eleves'
    | '/emploi-du-temps'
    | '/enseignants'
    | '/forgot-password'
    | '/login'
    | '/mon-abonnement'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/parent'
    | '/parents'
    | '/presences'
    | '/register'
    | '/scolarite'
    | '/sitemap.xml'
    | '/super-admin'
    | '/unauthorized'
    | '/eleves/$studentId'
    | '/api/public/admin-users'
    | '/api/public/register-school'
    | '/api/public/seed-demo'
    | '/api/public/super-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnoncesRoute: typeof AnnoncesRoute
  ChangerMotDePasseRoute: typeof ChangerMotDePasseRoute
  ClassesRoute: typeof ClassesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DashboardRoute: typeof DashboardRoute
  ElevesRoute: typeof ElevesRouteWithChildren
  EmploiDuTempsRoute: typeof EmploiDuTempsRoute
  EnseignantsRoute: typeof EnseignantsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MonAbonnementRoute: typeof MonAbonnementRoute
  MonProfilRoute: typeof MonProfilRoute
  NotesRoute: typeof NotesRoute
  ParametresRoute: typeof ParametresRoute
  ParentRoute: typeof ParentRoute
  ParentsRoute: typeof ParentsRoute
  PresencesRoute: typeof PresencesRoute
  RegisterRoute: typeof RegisterRoute
  ScolariteRoute: typeof ScolariteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiPublicAdminUsersRoute: typeof ApiPublicAdminUsersRoute
  ApiPublicRegisterSchoolRoute: typeof ApiPublicRegisterSchoolRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  ApiPublicSuperAdminRoute: typeof ApiPublicSuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scolarite': {
      id: '/scolarite'
      path: '/scolarite'
      fullPath: '/scolarite'
      preLoaderRoute: typeof ScolariteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presences': {
      id: '/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof PresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-profil': {
      id: '/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof MonProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-abonnement': {
      id: '/mon-abonnement'
      path: '/mon-abonnement'
      fullPath: '/mon-abonnement'
      preLoaderRoute: typeof MonAbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enseignants': {
      id: '/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof EnseignantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emploi-du-temps': {
      id: '/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof EmploiDuTempsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changer-mot-de-passe': {
      id: '/changer-mot-de-passe'
      path: '/changer-mot-de-passe'
      fullPath: '/changer-mot-de-passe'
      preLoaderRoute: typeof ChangerMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves/$studentId': {
      id: '/eleves/$studentId'
      path: '/$studentId'
      fullPath: '/eleves/$studentId'
      preLoaderRoute: typeof ElevesStudentIdRouteImport
      parentRoute: typeof ElevesRoute
    }
    '/api/public/super-admin': {
      id: '/api/public/super-admin'
      path: '/api/public/super-admin'
      fullPath: '/api/public/super-admin'
      preLoaderRoute: typeof ApiPublicSuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register-school': {
      id: '/api/public/register-school'
      path: '/api/public/register-school'
      fullPath: '/api/public/register-school'
      preLoaderRoute: typeof ApiPublicRegisterSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-users': {
      id: '/api/public/admin-users'
      path: '/api/public/admin-users'
      fullPath: '/api/public/admin-users'
      preLoaderRoute: typeof ApiPublicAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElevesRouteChildren {
  ElevesStudentIdRoute: typeof ElevesStudentIdRoute
}

const ElevesRouteChildren: ElevesRouteChildren = {
  ElevesStudentIdRoute: ElevesStudentIdRoute,
}

const ElevesRouteWithChildren =
  ElevesRoute._addFileChildren(ElevesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnoncesRoute: AnnoncesRoute,
  ChangerMotDePasseRoute: ChangerMotDePasseRoute,
  ClassesRoute: ClassesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DashboardRoute: DashboardRoute,
  ElevesRoute: ElevesRouteWithChildren,
  EmploiDuTempsRoute: EmploiDuTempsRoute,
  EnseignantsRoute: EnseignantsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MonAbonnementRoute: MonAbonnementRoute,
  MonProfilRoute: MonProfilRoute,
  NotesRoute: NotesRoute,
  ParametresRoute: ParametresRoute,
  ParentRoute: ParentRoute,
  ParentsRoute: ParentsRoute,
  PresencesRoute: PresencesRoute,
  RegisterRoute: RegisterRoute,
  ScolariteRoute: ScolariteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiPublicAdminUsersRoute: ApiPublicAdminUsersRoute,
  ApiPublicRegisterSchoolRoute: ApiPublicRegisterSchoolRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  ApiPublicSuperAdminRoute: ApiPublicSuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
